### PR TITLE
Fix spring-boot#481: add JRE_HOME

### PR DESCRIPTION
**Pull request by anthonydahanne**
* JRE_HOME is often used as a convention to convey the path of a JRE; in this case it's convenient to distinguish the JRE from a JDK (when both are required), since the PATH can insert the JRE_HOME/bin or JDK_HOME/bin in a non predictable order.
* Thanks to JRE_HOME, subsequent build steps will be able to use JRE_HOME/bin/java to make sure they pick a JRE and not a JDK
* in case there's just a JDK desired by the user, JRE_HOME will also be set, as the JDK_HOME

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Review by dmikusa — APPROVED** [review]
Looks good to me.

**Comment by dmikusa** [comment]
So if I have this correct.

At build time:

- `JRE_HOME` -> the JRE
- `JDK_HOME` -> the JDK
- `JAVA_HOME` -> the JDK (cause JRE is set to default, and JDK is set to override)

I'm curious what the behavior of PATH is here, given that both the JRE & JDK will be on PATH. I guess it depends on how the lifecycle processes the layers and puts them on the PATH? What have you observed @anthonydahanne ?

**Comment by dmikusa** [comment]
Should we also update the JLink installer? 

That presently sets `JAVA_HOME` at build time but not `JRE_HOME` or `JDK_HOME`. I'm not 100% sure what it should do though. Probably `JRE_HOME` cause we strip out the JDK part, at least by default, and you're guaranteed to have at least a JRE.

**Comment by anthonydahanne** [comment]
> At build time:

    JRE_HOME -> the JRE
    JDK_HOME -> the JDK
    JAVA_HOME -> the JDK (cause JRE is set to default, and JDK is set to override)

Almost: if the buildplan requires both JRE and JDK: JRE_HOME -> the JDK

> I'm curious what the behavior of PATH is here, given that both the JRE & JDK will be on PATH. I guess it depends on how the lifecycle processes the layers and puts them on the PATH? What have you observed @anthonydahanne ?

Well, PATH is kind of... not predictable. What I have observed is JDK path sometimes before, sometimes after JRE path in the PATH env.
So, that was not deterministic to call `java` from a `contribute` method, so that's why it's fixed using `JRE_HOME/bin/java`

> Should we also update the JLink installer?
That, I don't know. But... I supposed it's not required if nobody had any issues with it so far.

We had the issue with CDS training run: CDS MUST use the same JVM during training run and runtime; and because of PATH, it was not reliable

**Comment by dmikusa** [comment]
> Well, PATH is kind of... not predictable. What I have observed is JDK path sometimes before, sometimes after JRE path in the PATH env.

Interesting 🤔 I'm going to mention this upstream and see what they say.

> Almost: if the buildplan requires both JRE and JDK: JRE_HOME -> the JDK

Oh, that's not what I would have expected. Why would JRE_HOME point to the JDK? Isn't that what you're trying to avoid? Cause the JDK would run the CDS training, but then the JRE would run the app at runtime and they'd be different?

**Comment by anthonydahanne** [comment]
oh I'm sorry, I pressed enter too fast
I meant to say:
> Almost: if the buildplan requires ONLY a JDK (BP_JVM_TYPE=jdk): JRE_HOME -> the JDK

**Pull request merged**
